feat: reading trading data from disk and generating candlesticks for backtest execution
grinply/katetrade pull request #20
Opened 2024-10-26 19:42 UTC by victorl2

+ Added missing CLI parameters/implementation to call the backtester
+ Added candlestick parser for `tick` data ( trade by trade )
+ Added initilization of the backtest engine, loading trading data from local disk if available
+ Move implementation from `File` to `Trade`.

usage:
```
cargo run -- backtest --market FUTURES --ticker IND --begin 20240613 --end 20241024 --strategy DUMMY
```

2024-10-27 02:16 UTC, philippegeraldeli commented on src/services/backtest.rs
> +        }
I think this whole logic of validating date could be in a method apart from the main logic. 

Why not using NaiveDateTime, NaiveDate, NaiveTime chrono lib objects?

2024-10-27 02:16 UTC, philippegeraldeli commented on src/services/backtest.rs
> +                                        },
Why fixing candle strategy as tick? this is for mvp?

2024-10-27 02:44 UTC, aLexandreM1 requested changes
I'm request changes only for pattern stuffs.
If there's any reason to be like it, let me know and I change my position

2024-10-27 02:44 UTC, aLexandreM1 commented on src/main.rs
> +    } else {
early return is something common in rust?
if so, you could just remove this else

2024-10-27 02:44 UTC, aLexandreM1 commented on src/services/backtest.rs
> +        if start_date < 2000_01_01 || start_date > 3000_12_31 {
yyyyMMdd in your log/print next line but, yyyy_MM_dd in your comparision, is this normal/acceptable?

2024-10-27 02:44 UTC, aLexandreM1 commented on src/services/backtest.rs
> +        let start_day = start_date % 100;
Could you explain this logic?
I didn't get it well

2024-10-27 02:44 UTC, aLexandreM1 commented on src/services/backtest.rs
> +        if end_date < 2000_01_01 || end_date > 30001231 {
`2000_01_01` and `30001231`
I'm assuming both of them are acceptable, but should we have a pattern

2024-10-28 11:59 UTC, victorl2 commented on src/services/backtest.rs
> +        }
It was just simpler to handle everything in this method directly, we definally can refactor this out, if we want. I am not very familiar with the Date types from the chrono lib, i will take a look for the next iteration.

2024-10-28 12:01 UTC, victorl2 commented on src/services/backtest.rs
> +                                        },
Yes, we were going to use the `Trade` struct directly, but due to size implications dedicated to apply the candlestick instead, we still dont have the implementation for everything, this should be a future improvement for now, but shouldnt be a blocker to run any test in the data.

2024-10-28 12:03 UTC, victorl2 commented on src/main.rs
> +    } else {
Not sure how common it is, since it is allowed I dont see i problem for us to use it here, i will replace the else portion since it is not needed.

2024-10-28 12:03 UTC, victorl2 commented on src/services/backtest.rs
> +        if start_date < 2000_01_01 || start_date > 3000_12_31 {
Yes, underscores dont affect anything in the numbers, just make it easier for humans to read the values.

2024-10-28 12:04 UTC, merged

2024-10-28 12:05 UTC, victorl2 commented on src/services/backtest.rs
> +        if end_date < 2000_01_01 || end_date > 30001231 {
No, we actually added a cap in the dates, just didnt include a specific message for this.

2024-10-28 12:06 UTC, victorl2 commented on src/services/backtest.rs
> +        let start_day = start_date % 100;
If you work out the math given any number in the format yyyyMMdd this will extract the values such that

```
let start_year = yyyy;
let start_month = MM;
let start_day = dd;
```